"""added rent price per hour for device

Revision ID: 024b67220cf3
Revises: f7e2d2cd17c8
Create Date: 2024-05-02 12:22:07.881926

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '024b67220cf3'
down_revision: Union[str, None] = 'f7e2d2cd17c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('rent_price_per_hour', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'rent_price_per_hour')
    # ### end Alembic commands ###
