"""Updated Structure

Revision ID: 6244219e1b24
Revises: a6e31d81ec4d
Create Date: 2024-04-28 17:42:24.449950

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6244219e1b24'
down_revision: Union[str, None] = 'a6e31d81ec4d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lockers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('campus', sa.String(), nullable=False),
    sa.Column('room', sa.String(), nullable=False),
    sa.Column('size', sa.String(), nullable=False),
    sa.Column('rent_charge', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('devices', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('devices', sa.Column('category_id', sa.Integer(), nullable=False))
    op.alter_column('devices', 'owner',
                    existing_type=sa.VARCHAR(),
                    type_=sa.Integer(),
                    postgresql_using='owner::integer',
                    nullable=False)
    op.alter_column('devices', 'date_of_purchase',
                    existing_type=sa.DATE(),
                    type_=sa.DateTime(),
                    nullable=False)
    op.alter_column('devices', 'price',
                    existing_type=sa.DOUBLE_PRECISION(precision=53),
                    nullable=False)
    op.alter_column('devices', 'brand',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('devices', 'model',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('devices', 'serial_no',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.alter_column('devices', 'qr_code',
                    existing_type=sa.VARCHAR(),
                    nullable=False)
    op.drop_index('ix_devices_ID', table_name='devices')
    op.create_table('bookings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_start', sa.DateTime(), nullable=False),
    sa.Column('time_end', sa.DateTime(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rent_charge', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'devices', ['qr_code'])
    op.create_unique_constraint(None, 'devices', ['serial_no'])
    op.create_foreign_key(None, 'devices', 'categories', ['category_id'], ['id'])
    op.create_foreign_key(None, 'devices', 'users', ['owner'], ['id'])
    op.drop_column('devices', 'ID')
    op.add_column('users', sa.Column('name', sa.String(), nullable=False))
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'users', ['email'])
    op.drop_column('users', 'password')
    op.drop_column('users', 'firstname')
    op.drop_column('users', 'lastname')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lastname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('firstname', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'name')
    op.add_column('devices', sa.Column('ID', sa.INTEGER(), server_default=sa.text('nextval(\'"devices_ID_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='unique')
    op.drop_constraint(None, 'devices', type_='unique')
    op.create_index('ix_devices_ID', 'devices', ['ID'], unique=False)
    op.alter_column('devices', 'qr_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'serial_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'model',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'brand',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('devices', 'price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('devices', 'date_of_purchase',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)
    op.alter_column('devices', 'owner',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=True)
    op.drop_column('devices', 'category_id')
    op.drop_column('devices', 'id')
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('bookings')
    op.drop_table('reports')
    op.drop_table('lockers')
    # ### end Alembic commands ###

