"""Updated Device Model

Revision ID: 658afeaf6c6d
Revises: 1a0f25853bee
Create Date: 2024-04-29 11:22:26.483104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '658afeaf6c6d'
down_revision: Union[str, None] = '1a0f25853bee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'qr_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('devices', 'qr_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
