"""Added Pin to Booking

Revision ID: d28296efa7df
Revises: 1cdfc22a0b5f
Create Date: 2024-04-30 18:11:08.590900

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd28296efa7df'
down_revision: Union[str, None] = '1cdfc22a0b5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('pin', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bookings', 'pin')
    # ### end Alembic commands ###
