"""added purchase price for booking

Revision ID: f7e2d2cd17c8
Revises: aa13541d3960
Create Date: 2024-05-02 11:17:32.352355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7e2d2cd17c8'
down_revision: Union[str, None] = 'aa13541d3960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('booking_price', sa.Float(), nullable=True))
    op.drop_column('bookings', 'price')
    op.add_column('devices', sa.Column('purchase_price', sa.Float(), nullable=True))
    # Convert date_of_purchase from VARCHAR to TIMESTAMP WITHOUT TIME ZONE
    op.execute("ALTER TABLE devices ALTER COLUMN date_of_purchase TYPE TIMESTAMP WITHOUT TIME ZONE USING date_of_purchase::timestamp without time zone")
    op.drop_column('devices', 'price')
    # Convert date column from VARCHAR to TIMESTAMP WITHOUT TIME ZONE
    op.execute("ALTER TABLE reports ALTER COLUMN date TYPE TIMESTAMP WITHOUT TIME ZONE USING date::timestamp without time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert date column back to VARCHAR
    op.execute("ALTER TABLE reports ALTER COLUMN date TYPE VARCHAR")
    op.add_column('devices', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    # Convert date_of_purchase back to VARCHAR
    op.execute("ALTER TABLE devices ALTER COLUMN date_of_purchase TYPE VARCHAR")
    op.drop_column('devices', 'purchase_price')
    op.add_column('bookings', sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('bookings', 'booking_price')
    # ### end Alembic commands ###
