"""empty message

Revision ID: 01287cae4d14
Revises: f41190c2ef50
Create Date: 2024-04-20 14:32:13.722140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01287cae4d14'
down_revision = 'f41190c2ef50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
