"""empty message

Revision ID: 730349e16058
Revises: d0cdb03dc4fe
Create Date: 2024-04-20 14:50:48.702853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '730349e16058'
down_revision = 'd0cdb03dc4fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'age')
    # ### end Alembic commands ###
