"""empty message

Revision ID: 9c3cd70f87ba
Revises: c81b7a60cb27
Create Date: 2024-04-18 17:33:16.574991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c3cd70f87ba'
down_revision = 'c81b7a60cb27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
