"""empty message

Revision ID: ab64239b1815
Revises: 15524709d8ba
Create Date: 2024-04-20 13:57:06.212977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ab64239b1815'
down_revision = '15524709d8ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
