"""empty message

Revision ID: d3328b2ed084
Revises: ab64239b1815
Create Date: 2024-04-20 13:58:14.032561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3328b2ed084'
down_revision = 'ab64239b1815'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
