"""Add new column to User table

Revision ID: f0c538025c5d
Revises: 8413a7fa543a
Create Date: 2024-04-20 14:27:39.585854

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0c538025c5d'
down_revision = '8413a7fa543a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
