"""empty message

Revision ID: f41190c2ef50
Revises: f0c538025c5d
Create Date: 2024-04-20 14:31:49.522472

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f41190c2ef50'
down_revision = 'f0c538025c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
